#First one#

In [1]:
print("Hello")

Hello

In [2]:
import numpy as np

In [73]:
a = np.array([[1,2,3],[99,88,77]])
a

array([[ 1,  2,  3],
       [99, 88, 77]])

In [75]:
ar = np.random.rand(2,3)
ar

array([[0.53564695, 0.06347493, 0.95633839],
       [0.33384389, 0.453893  , 0.00305868]])

In [93]:
ar.ndim
ar.shape
ar.size

6

In [81]:
ar = np.random.randint(10)
ar

5

In [88]:
arr = np.zeros([2,3], dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [89]:
arr = np.full([2,4], 22)
arr

array([[22, 22, 22, 22],
       [22, 22, 22, 22]])

In [87]:
ar = np.array([1,2,3], dtype=np.float64)
ar

array([1., 2., 3.])

In [94]:
arr = np.arange(1,20, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
arr = np.random.randint(10,200)
arr

118

Reshape

In [98]:
ar = np.array([1,2,3,4,5,6])
res = ar.reshape(2,3)
res

array([[1, 2, 3],
       [4, 5, 6]])

Ravel vs flatten

In [103]:
nested_array = np.array([[1, 2, 3], [4, 5, 6]])

flattened = nested_array.flatten()
flattened

array([1, 2, 3, 4, 5, 6])

Arithematics ops in Numpy

In [108]:
a = np.array([1,2,3])
b = np.array([9,8,7])

a**3

array([ 1,  8, 27])

Indexing and Slicing

In [112]:
arr = np.array([10, 20, 30, 40 , 50])

arr[:4:2]

# for slice in arr ->  [start:end:step]

array([10, 30])

In [113]:
arr = np.array([10, 20, 30, 40 , 50])
arr_c = arr.copy()
arr_c

array([10, 20, 30, 40, 50])

Tranpose

In [116]:
arr = np.random.rand(2,3)
print(arr)
arr_t = arr.transpose()
arr_t

[[0.03956728 0.04323045 0.43553601]
 [0.98071563 0.76600254 0.72976523]]

array([[0.03956728, 0.98071563],
       [0.04323045, 0.76600254],
       [0.43553601, 0.72976523]])

Concat/stack

In [ ]:
a = np.array([1,2,3])
b = np.array([9,8,7])
c= np.hstack((a,b)) # concacat
d = np.vstack((a,b)) # Stack

array([[1, 2, 3],
       [9, 8, 7]])

In [15]:
arr = np.array([[1,2,3],[9,8,7],[1,1,1]])
arr.ravel()

array([1, 2, 3, 9, 8, 7, 1, 1, 1])

In [22]:
my_dict = {
    "name": "Shivu",
    "age": 25,
    "city": "Bangalore"
}

print(my_dict)

{'name': 'Shivu', 'age': 25, 'city': 'Bangalore'}

In [26]:
import pandas as pd

sr = pd.Series(my_dict, name = 'pp')
sr

name        Shivu
age            25
city    Bangalore
Name: pp, dtype: object

In [63]:
employees = [
    {"EMPNO": 7369, "ENAME": "SMITH",  "JOB": "CLERK",    "MGR": 7902, "HIREDATE": "17-DEC-80", "SAL": 800,  "COMM": None, "DEPTNO": 20},
    {"EMPNO": 7499, "ENAME": "ALLEN",  "JOB": "SALESMAN", "MGR": 7698, "HIREDATE": "20-FEB-81", "SAL": 1600, "COMM": 300,  "DEPTNO": 30},
    {"EMPNO": 7521, "ENAME": "WARD",   "JOB": "SALESMAN", "MGR": 7698, "HIREDATE": "22-FEB-81", "SAL": 1250, "COMM": 500,  "DEPTNO": 30},
    {"EMPNO": 7566, "ENAME": "JONES",  "JOB": "MANAGER",  "MGR": 7839, "HIREDATE": "02-APR-81", "SAL": 2975, "COMM": None, "DEPTNO": 20},
    {"EMPNO": 7654, "ENAME": "MARTIN", "JOB": "SALESMAN", "MGR": 7698, "HIREDATE": "28-SEP-81", "SAL": 1250, "COMM": 1400, "DEPTNO": 30},
    {"EMPNO": 7698, "ENAME": "BLAKE",  "JOB": "MANAGER",  "MGR": 7839, "HIREDATE": "01-MAY-81", "SAL": 2850, "COMM": None, "DEPTNO": 30},
    {"EMPNO": 7782, "ENAME": "CLARK",  "JOB": "MANAGER",  "MGR": 7839, "HIREDATE": "09-JUN-81", "SAL": 2450, "COMM": None, "DEPTNO": 10},
    {"EMPNO": 7788, "ENAME": "SCOTT",  "JOB": "ANALYST",  "MGR": 7566, "HIREDATE": "19-APR-87", "SAL": 3000, "COMM": None, "DEPTNO": 20},
    {"EMPNO": 7839, "ENAME": "KING",   "JOB": "PRESIDENT","MGR": None, "HIREDATE": "17-NOV-81", "SAL": 5000, "COMM": None, "DEPTNO": 10},
    {"EMPNO": 7844, "ENAME": "TURNER", "JOB": "SALESMAN", "MGR": 7698, "HIREDATE": "08-SEP-81", "SAL": 1500, "COMM": 0,    "DEPTNO": 30},
    {"EMPNO": 7876, "ENAME": "ADAMS",  "JOB": "CLERK",    "MGR": 7788, "HIREDATE": "23-MAY-87", "SAL": 1100, "COMM": None, "DEPTNO": 20},
    {"EMPNO": 7900, "ENAME": "JAMES",  "JOB": "CLERK",    "MGR": 7698, "HIREDATE": "03-DEC-81", "SAL": 950,  "COMM": None, "DEPTNO": 30},
    {"EMPNO": 7902, "ENAME": "FORD",   "JOB": "ANALYST",  "MGR": 7566, "HIREDATE": "03-DEC-81", "SAL": 3000, "COMM": None, "DEPTNO": 20},
    {"EMPNO": 7934, "ENAME": "MILLER", "JOB": "CLERK",    "MGR": 7782, "HIREDATE": "23-JAN-82", "SAL": 1300, "COMM": None, "DEPTNO": 10}
]

df = pd.DataFrame(employees)
df

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     NaN      30
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     NaN      10

In [64]:
def rename_column(col):
    col = col.lower()  # CAPS → lower
    # col = '_'.join(col)
    return col

In [65]:
df = df.rename(rename_column, axis=1)
df

    empno   ename        job     mgr   hiredate   sal    comm  deptno
0    7369   SMITH      CLERK  7902.0  17-DEC-80   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-81  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  22-FEB-81  1250   500.0      30
3    7566   JONES    MANAGER  7839.0  02-APR-81  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-81  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  01-MAY-81  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0  09-JUN-81  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0  19-APR-87  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  17-NOV-81  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0  08-SEP-81  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  23-MAY-87  1100     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-81   950     NaN      30
12   7902    FORD    ANALYST  7566.0  03-DEC-81  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  23-JAN-82  1300     NaN      10